### ISSUE TITLE
Fails in jQuery 1.4.2 if callback is not defined

### ISSUE THREAD

**Issue by austegard** [cowboy/jquery-throttle-debounce#1]
We had to add a check to verify that callback was defined as follows (line 189) - otherwise the wrapper.guid assignment failed catastrophically:

```
    // Set the guid of `wrapper` function to the same of original callback, so
    // it can be removed in jQuery 1.4+ .unbind or .die by using the original
    // callback as a reference.
    if ($.guid && callback) {
          wrapper.guid = callback.guid = callback.guid || $.guid++;
    }
```

**Comment by cowboy** [comment]
I don't understand... when would `callback` not be defined?

**Comment by austegard** [comment]
Huh - this just happened again, and the obvious reason was that the callback function was indeed not defined (thanks SVN merge...).

_This is NOT a throttle-debounce issue._
