### ISSUE TITLE
d3.js mousemove

### ISSUE THREAD

**Issue by alen-z** [cowboy/jquery-throttle-debounce#18]
I am using d3.js library.

.on( "mousemove", $.throttle(1000, false, function() { console.log(d3.mouse(this) }) )

This returns only 1st result and some random good results afterwards. In general, it returns error:
[Error] TypeError: null is not an object (evaluating 't.sourceEvent')
    b (d3.min.js, line 1)
    mouse (d3.min.js, line 3)
    (anonymous function) (index.html, line 74)
    exec (jquery.ba-throttle-debounce.js, line 149)

If true is used for no_trailing it works but without the last event data (of course). I need false no_trailing.

**Comment by cinan** [comment]
how did you solve it?
