### ISSUE TITLE
passing parameters to callback?

### ISSUE THREAD

**Issue by janusch** [cowboy/jquery-throttle-debounce#19]
Is it possible to pass arguments to the callback function?
e.g.:

``` js
$(window).scroll($.debounce(40, updateLeftOffset(el, offset)));
```

This example throws an error right now. Is there a specific reason why this is not desired?

Is this sweet little plugin still maintained?

**Comment by martinml** [comment]
You can't do that because you'd be calling the `updateLeftOffset()` function when that line was executed, and not in the scroll event.

You have to do something like this:

``` javascript
$(window).scroll($.debounce(40, function() {
    updateLeftOffset(el, offset));
}));
```

**Comment by janusch** [comment]
@martinml thanks for the reply.
This looks like a good solution, I have not tried it yet, but the issue is closed i believe.

Thanks for pointing this out!
