### ISSUE TITLE
undefined jquery "guid" property

### ISSUE THREAD

**Issue by jfinkels** [cowboy/jquery-throttle-debounce#4]
With the following HTML

``` html
  <html>
    <head>
      <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
      <script type="text/javascript" src="./jquery.ba-throttle-debounce.js"></script>

      <script type="text/javascript">
        $.debounce(function() {});
      </script>

    </head>
  </html>
```

I get the following traceback:

```
  Uncaught TypeError: Cannot read property 'guid' of undefined
    at "$.throttle.jq_throttle" in jquery.ba-throttle-debounce.js:190
    at "$.debounce" jquery.ba-throttle-debounce.js:248
    at (anonymous function) in foo.html:6
```

I am using Chromium 11 on Ubuntu.

**Comment by cowboy** [comment]
You need to specify a delay as the first argument, like so:

``` javascript
$.debounce(100, function() {});
```

**Comment by jfinkels** [comment]
thanks

**Comment by paladini** [comment]
I'm having the same issue today, but I'm specifying delay as the first argument. My code is something like:

``` javascript
$('input').on('input keyup', function(){

    ...some code...
    $.debounce(200, autoComplete(e));
});

function autoComplete(e){
    var eventKeyCode = e.which;
    ...
} 
```

Chrome console gives me the following:

```
Uncaught TypeError: Cannot read property 'guid' of undefined 
    $.throttle.a vendor.js:58
    $.debounce vendor.js:58
    (anonymous function) vendor.js:467
    x.event.dispatch vendor.js:6
    v.handle
```

Currently my code seems to be working properly, but this error is fired when I modify anything on input, and this is so undesirable. Thanks and hope you can help me! :)

**Comment by loadedsith** [comment]
switching from 

`$.debounce( 250, scrollManager.scrollToNextSection());` 

to 

`$.debounce( 250, function(){scrollManager.scrollToNextSection()});`

hid the error, but did not solve the issue.

Looking more closely at the examples I realized the method may not be valid to use anywhere i like, so i wrapped the event binding with `$.debounce()` and have solved the issue:

`
$(window).scroll($.debounce( 250, function (e) {//your already debounced logic here}));
`

**Comment by iaian** [comment]
I just ran into this issue as well. Solved by looking over the examples : http://benalman.com/code/projects/jquery-throttle-debounce/examples/throttle/. 

Making sure you are using the plugin correctly.

old and busted :
`$(window).resize( $.throttle( 250, _onResize() ) );`

new and working :
`$(window).resize( $.throttle( 250, _onResize ) );`

**Comment by slpixe** [comment]
thanks @iaian, removing the arguments from the function call works

**Comment by hourdays** [comment]
Same issue but I need to pass an argument to my resize so I don't understand...

**Comment by Cian911** [comment]
I'm having the same issue as @hourdays has there been a solution for this?

**EDIT**

I solved the issue by doing the below:

`$('#complaint-faq-search-internal').on(
          'keyup',
          $.throttle(
            250,
            function() {
              searchKnowledgeBase($(this), true, 10);
            }
          )
        );`

**Comment by dimosr** [comment]
@hourdays , @Cian911 I was trying to handle approximately the same issue. Besides wanting to add parameters, I wanted to call a function on a specific object (i.e. `myObject.myFunc()`). So, instead of:
$( window ).resize({handler: this}, function(event) {
$.debounce( 250, function(){event.data.handler.reEnableSideWidget()} )();
});

**Comment by dimosr** [comment]
@hourdays , @Cian911 I was trying to handle approximately the same issue. Besides wanting to add parameters, I wanted to call a function on a specific object (i.e. `myObject.myFunc()`). So, instead of:

``` javascript
$( window ).resize(function(event) {
      $.debounce( 250, myObject.myFunc() );
});
```

or

``` javascript
$( window ).resize(function(event) {
      $.debounce( 250,  function(){myObject.myFunc()} );
});
```

I had to use:

``` javascript
$( window ).resize(function(event) {
      $.debounce( 250,  function(){myObject.myFunc()} )();
});
```

which worked normally, without throwing the error.

**Comment by delcon** [comment]
@dimosr , I tried your solution for throttle. It did call the function but without throttling¨!

I switched to _underscore and  got it working this way:

`
var throttled = _.throttle(functionToCall, 1000);
`

then invoke the function like this:

`
throttled(param);
`

you should be able to use parameters like this

**Comment by Drumstix42** [comment]
This was confusing to me first as well. But I figured it out.

This defines your function with any parameters you want:
`var test = function(input){ console.log(input); }`

This defines that you want to be able to call this function with the throttle/bounce functionality:
`var testThrottle = $.throttle(1000, test);`

This lets you call your function with parameters via the throttle/debounce:
`testThrottle("success!");`

This wasn't overly obvious to me, maybe I just didn't understand the examples, but this is working for me now.

**Comment by dearsina** [comment]
@Drumstix42 that was super helpful. What I have done on the back of your comment was to change my function from:
```
function functionName(var){
	console.log(var);
}
```
to
```
var functionName = $.debounce(1000, function(var){
	console.log(var);
});
```
This way, all my `functionName(var);` calls can remain as they are, except now they have an added debounce. I'm sorry if this is Javascript 101, but it was news to me!
