### ISSUE TITLE
Debouncing an existing an existing listener

### ISSUE THREAD

**Issue by dkvdm** [cowboy/jquery-throttle-debounce#6]
Hey Ben,

I'm using [FCBKcomplete](http://www.emposha.com/javascript/fcbkcomplete.html), which is basically a Facebook-esque lookup via ajax for jQuery. However, the current implementation checks on every keystroke, which it does via it's own listener.

Here is how I'm using it on doc ready:

``` javascript
$("#tagselect").fcbkcomplete({
        json_url: "/gettags",
        cache: true,
        filter_case: false,
        filter_hide: true,
        firstselected: true,
        filter_selected: true,
        addontab: true,
        maxitems: 5,
        newel: true,
    });
```

Since it already has a listener for keypresses, how can I debounce this?

Much obliged,
Dennis

**Comment by cowboy** [comment]
I can't think of a way, short of modifying FCBKcomplete's code.
